apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app-cluster-ip
  namespace: stateless-apps
spec:
  ports:
  - name: app-http
    port: 80
    protocol: TCP
    targetPort: app-http
#    targetPort: 80
  selector:
    app: my-app
    type: web-app
  type: ClusterIP
